/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MoodScoreTestInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getEncryptedAnswerCount"
      | "getEncryptedTotalScore"
      | "getTestMeta"
      | "hasSubmitted"
      | "protocolId"
      | "submitMoodTest"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "MoodScoreDecrypted" | "MoodTestSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getEncryptedAnswerCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedTotalScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTestMeta",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasSubmitted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitMoodTest",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getEncryptedAnswerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedTotalScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTestMeta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasSubmitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitMoodTest",
    data: BytesLike
  ): Result;
}

export namespace MoodScoreDecryptedEvent {
  export type InputTuple = [
    user: AddressLike,
    totalScore: BigNumberish,
    answerCount: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    totalScore: bigint,
    answerCount: bigint
  ];
  export interface OutputObject {
    user: string;
    totalScore: bigint;
    answerCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MoodTestSubmittedEvent {
  export type InputTuple = [user: AddressLike, createdAt: BigNumberish];
  export type OutputTuple = [user: string, createdAt: bigint];
  export interface OutputObject {
    user: string;
    createdAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MoodScoreTest extends BaseContract {
  connect(runner?: ContractRunner | null): MoodScoreTest;
  waitForDeployment(): Promise<this>;

  interface: MoodScoreTestInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getEncryptedAnswerCount: TypedContractMethod<
    [user: AddressLike],
    [string],
    "view"
  >;

  getEncryptedTotalScore: TypedContractMethod<
    [user: AddressLike],
    [string],
    "view"
  >;

  getTestMeta: TypedContractMethod<
    [user: AddressLike],
    [[bigint, boolean] & { createdAt: bigint; exists: boolean }],
    "view"
  >;

  hasSubmitted: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  submitMoodTest: TypedContractMethod<
    [
      encryptedTotalScore: BytesLike,
      encryptedAnswerCount: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getEncryptedAnswerCount"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedTotalScore"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTestMeta"
  ): TypedContractMethod<
    [user: AddressLike],
    [[bigint, boolean] & { createdAt: bigint; exists: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasSubmitted"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitMoodTest"
  ): TypedContractMethod<
    [
      encryptedTotalScore: BytesLike,
      encryptedAnswerCount: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "MoodScoreDecrypted"
  ): TypedContractEvent<
    MoodScoreDecryptedEvent.InputTuple,
    MoodScoreDecryptedEvent.OutputTuple,
    MoodScoreDecryptedEvent.OutputObject
  >;
  getEvent(
    key: "MoodTestSubmitted"
  ): TypedContractEvent<
    MoodTestSubmittedEvent.InputTuple,
    MoodTestSubmittedEvent.OutputTuple,
    MoodTestSubmittedEvent.OutputObject
  >;

  filters: {
    "MoodScoreDecrypted(address,uint256,uint256)": TypedContractEvent<
      MoodScoreDecryptedEvent.InputTuple,
      MoodScoreDecryptedEvent.OutputTuple,
      MoodScoreDecryptedEvent.OutputObject
    >;
    MoodScoreDecrypted: TypedContractEvent<
      MoodScoreDecryptedEvent.InputTuple,
      MoodScoreDecryptedEvent.OutputTuple,
      MoodScoreDecryptedEvent.OutputObject
    >;

    "MoodTestSubmitted(address,uint64)": TypedContractEvent<
      MoodTestSubmittedEvent.InputTuple,
      MoodTestSubmittedEvent.OutputTuple,
      MoodTestSubmittedEvent.OutputObject
    >;
    MoodTestSubmitted: TypedContractEvent<
      MoodTestSubmittedEvent.InputTuple,
      MoodTestSubmittedEvent.OutputTuple,
      MoodTestSubmittedEvent.OutputObject
    >;
  };
}
